My_Django_stuff/first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('filter/',views.filter,name='filter'),
    path('movie1/',views.movie1,name='movie1'),
    path('play/',views.play,name='play'),
]

My_Django_stuff/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.urls import include

urlpatterns = [
    path('',views.index,name='index'),
    path('first_app/',include('first_app.urls')),
    path('admin/', admin.site.urls),
]

My_Django_stuff/first_project/first_app/models.py
from django.db import models

# Create your models here.

My_Django_stuff/first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request,'first_app/index.html')

def filter(request):
    return render(request,'first_app/filter.html')

def movie1(request):
    return render(request,'first_app/movie1.html')

def play(request):
    return render(request,'first_app/play.html')

My_Django_stuff/first_project/templates/first_app/filter.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>webmovies</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/mystyle.css" %}"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap" rel="stylesheet">


  </head>
  <body class="body">



    <div class="topnav">
     <a class="active" href="#home"> وب موویز </a>
     <a href="{% url 'first_app:index'%}"> خانه </a>
     <a href="{% url 'first_app:filter'%}">فیلتر</a>
     <button class="navbutton"><a href="#login"> ورود/ثبت نام </a></button>
     <button class="navbutton"><a href="#buy"> خرید اشتراک </a></button>
    </div>

    <div class="filtr">

      <form >
      <input type="text" class="search" placeholder="جستجو" name="search">
      <button type="submit" class="sb"><img src="{% static "images/search.png" %}" class="simg"></button>
     </form>


      <table class="lists">
        <tr class="trlists">
          <th class="thlists" colspan="2" >ژانر</th>
          <th class="thlists">کشور سازنده</th>
          <th class="thlists">مرتب سازی براساس</th>
        </tr>
        <tr>
          <td class="tdlists">
            <label class="container"> اجتماعی
              <input type="checkbox" >
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> اکشن
              <input type="checkbox" >
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> ایران
              <input type="checkbox" >
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> مرتبط ترین
              <input type="checkbox" checked="checked">
              <span class="checkmark"></span>
            </label>
          </td>
        </tr>
        <tr>
          <td class="tdlists">
            <label class="container"> انیمیشن
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> تاریخی
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> آمریکا
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> تازه های وب موویز
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
        </tr>
        <tr>
          <td class="tdlists">
            <label class="container"> ترسناک
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> جنایی
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container">  هند
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> امتیاز IMDB
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
        </tr>
        <tr>
          <td class="tdlists">
            <label class="container"> خانوادگی
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> درام
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> کره جنوبی
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
          <td class="tdlists">
            <label class="container"> سال ساخت
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </td>
        </tr>

      </table>


    </div>

    <div class="spacef"></div>
    <div class="footer-con">
      <div class="footer">
        <table align="center" class="tfooter">
          <tr>
            <td class="td"><a href="#" class="tdhover"> درباره وب موویز </a></td>
            <td class="td"><a href="#" class="tdhover"> تماس با ما </a></td>
          </tr>
          <tr>
            <td class="td"><a href="#" class="tdhover"> اپلیکشن ها </a></td>
            <td class="td"><a href="#" class="tdhover"> خرید اشتراک </a></td>
          </tr>
          <tr>
            <td class="td"><a href="#" class="tdhover">سوالات متداول</a></td>
            <td class="td"><a href="#" class="tdhover">قوانین و مقررات</a><td>
          </tr>
       </table>
       <div class="social"><a class="sociala"><img src="{% static "images/insta1.png" %}" class="icon"></a>
         <a class="sociala"><img src="{% static "images/Twitter.png" %}" class="icon"></a>
         <a class="sociala"><img src="{% static "images/tele.png" %}" class="icon"></a></div>
         <div class="endtext">
           <p> طراحی شده توسط احسانه طالب </p>
         </div>
       </div>
     </div>

  </body>
</html>

My_Django_stuff/first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>webmovies</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/mystyle.css" %}"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap" rel="stylesheet">


  </head>
  <body class="body">



    <div class="topnav">
     <a class="active" href="#home"> وب موویز </a>
     <a href="{% url 'first_app:index'%}"> خانه </a>
     <a href="{% url 'first_app:filter'%}">فیلتر</a>
     <button class="navbutton"><a href="#login"> ورود/ثبت نام </a></button>
     <button class="navbutton"><a href="#buy"> خرید اشتراک </a></button>
    </div>


    <div class="slideshow-container">

      <div class="mySlides">
        <img src="{% static "images/soul.jpeg" %}" class="imgslide" style="width:100%">
        <a href="#soul"><img src="{% static "images/soul.png" %}" class="name" title=" انیمیشن روح "></a>
        <div class="topright"><a href="#soul"> روح </a></div>
        <button class="infobutton"><a href="{% url 'first_app:movie1'%}"> اطلاعات فیلم</a></button>
      </div>

      <div class="mySlides">
        <img src="{% static "images/wwy.jpg" %}" class="imgslide" style="width:100%">
        <a href="#wwy"><img src="{% static "images/wwy.png" %}" class="name" title=" دختر آب و هوا "></a>
        <div class="topright"><a href="#wwy"> دختر آب وهوا </a></div>
        <button class="infobutton"><a href="#info"> اطلاعات فیلم</a></button>
      </div>

      <div class="mySlides">
        <img src="{% static "images/yoda.jpg" %}" class="imgslide" style="width:100%">
        <a href="#mando"><img src="{% static "images/mando1.png" %}" class="name" title=" سریال مندلورین "></a>
        <div class="topright"><a href="#mand">مندلورین  </a></div>
        <button class="infobutton"><a href="#info"> اطلاعات فیلم</a></button>
      </div>

      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>

      </div>

      <script type="text/javascript" src="{% static "javascript/javascript.js" %}"></script>

   <!-- image gallery -->

      <h3> ویژه </h3>
      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_5terre.jpg">
            <img class="image" src="{% static "images/aot1.jpg" %}"  width="600" height="400">
            <div class="text">8.9: IMDB<br>سریال حمله به تایتان <br>۲۰۱۳-انیمیشن-اکشن-ماجراجویی</div>
         </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_forest.jpg">
            <img class="image" src="{% static "images/mando1.jpg" %}"  width="600" height="400">
            <div class="text">8.8: IMDB<br>سریال مندلورین<br>۲۰۱۹-اکشن-ماجراجویی-علمی تخیلی</div>
          </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_lights.jpg">
            <img class="image" src="{% static "images/toy1.jpg" %}"  width="600" height="400">
            <div class="text">7.8: IMDB<br>داستان اسباب بازی های ۴<br>۲۰۱۹-انیمیشن-ماجراجویی-کمدی</div>
          </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_mountains.jpg">
            <img class="image" src="{% static "images/joker1.jpg" %}" width="600" height="400">
            <div class="text">8.4: IMDB<br>جوکر<br>۲۰۱۹-جنایی-هیجان انگیز-درام</div>
          </a>
        </div>
      </div>

      <h3>تازه های وب موویز</h3>
      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_5terre.jpg">
            <img class="image" src="{% static "images/st.jpg" %}"  width="600" height="400">
            <div class="text">8.7: IMDB<br>سریال چیزهای عجیبی<br>۲۰۱۶-درام-فانتزی-ترسناک</div>
         </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_forest.jpg">
            <img class="image" src="{% static "images/tdat.jpg" %}"  width="600" height="400">
            <div class="text">7.1: IMDB<br>شیطان تمام وقت<br>۲۰۲۰-جنایی-درام-هیجان انگیز</div>
          </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_lights.jpg">
            <img class="image" src="{% static "images/tlt.jpeg" %}"  width="600" height="400">
            <div class="text">6.3: IMDB<br>چیزهای کوچک<br>۲۰۲۱-جنایی-درام-هیجان انگیز</div>
          </a>
        </div>
      </div>

      <div class="responsive">
        <div class="gallery">
          <a target="_blank" href="img_mountains.jpg">
            <img class="image" src="{% static "images/mdb.jpg" %}" alt="Mountains" width="600" height="400">
            <div class="text">8.1: IMDB<br>دختر میلیون دلاری<br>۲۰۰۴-درام-ورزشی</div>
          </a>
        </div>
      </div>

  <!--    <div class="clearfix"></div>  -->
      <div class="space"></div>
      <div class="footer-con">
        <div class="footer">
          <table align="center" class="tfooter">
            <tr>
              <td class="td"><a href="#" class="tdhover"> درباره وب موویز </a></td>
              <td class="td"><a href="#" class="tdhover"> تماس با ما </a></td>
            </tr>
            <tr>
              <td class="td"><a href="#" class="tdhover"> اپلیکشن ها </a></td>
              <td class="td"><a href="#" class="tdhover"> خرید اشتراک </a></td>
            </tr>
            <tr>
              <td class="td"><a href="#" class="tdhover">سوالات متداول</a></td>
              <td class="td"><a href="#" class="tdhover">قوانین و مقررات</a><td>
            </tr>
         </table>
         <div class="social"><a class="sociala"><img src="{% static "images/insta1.png" %}" class="icon"></a>
           <a class="sociala"><img src="{% static "images/Twitter.png" %}" class="icon"></a>
           <a class="sociala"><img src="{% static "images/tele.png" %}" class="icon"></a></div>
           <div class="endtext">
             <p> طراحی شده توسط احسانه طالب </p>
           </div>
         </div>
       </div>
  </body>
</html>

My_Django_stuff/first_project/templates/first_app/movie1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>webmovies</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css'%}"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap" rel="stylesheet">


  </head>
  <body class="body">



    <div class="topnav">
     <a class="active" href="#home"> وب موویز </a>
     <a href="{% url 'first_app:index'%}"> خانه </a>
     <a href="{% url 'first_app:filter'%}">فیلتر</a>
     <button class="navbutton"><a href="#login"> ورود/ثبت نام </a></button>
     <button class="navbutton"><a href="#buy"> خرید اشتراک </a></button>
    </div>


    <div class="movie">
      <img src="{% static 'images/soul1.jpg' %}" class="imgmovie" >
      <a href="#soul"><img src="{% static 'images/soul.png' %}" class="namem" title=" انیمیشن روح "></a>
      <div class="toprightm"><a href="#soul"> روح </a><br></div>
      <div class="toprightp"><p> ۲۰۲۰ </p><p> ۱۲۷ دقیقه </p><p> IMDB 8.1 </p></div>
      <div class="detail">جو معلم موسیقی در یک مدرسه است. او از زندگی و کار خود ناراضی است و تصمیم می گیرد<br>به یک گروه موسیقی جاز بپیوندد، اما به طور ناگهانی روح او از بدنش جدا شده و با اتفاقاتی<br>غیرمنتظره روبرو می شود و...</div>
      <a href="#" class="aplay"><button class="play"> ورود و پخش فیلم </button></a>
      <a href="#" class="adownload"><img src="{% static 'images/download.png'%}" class="download"></a>
    </div>

    <div class="movieinfo">
        <h4 class="h4">درباره فیلم روح</h4>
        <p class="infotext">فیلم روح، فیلمی انیمیشن، ماجراجویی، کمدی، خانوادگی، فانتزی و موزیکال، محصول سال ۲۰۲۰ کشور آمریکا به کارگردانی پیتر داکتر و کمپ پاورز است. نویسندگی فیلم روح توسط پیت داکتر و مایک جونز انجام شده است. بازیگرانی چون جیمی فاکس، تینا فی، گراهام نورتون، ریچل هاوس، آلیس براگا، ریچارد آیود، فیلیسیا رشاد و دانل راولینگز در فیلم روح به ایفای نقش پرداخته اند.<br>
      فیلم روح توسط استودیوی انیمیشن پیکسار تولید شده و پخش آن توسط شرکت والت دیزنی صورت گرفته است. انیمیشن روح اندکی پس از اکران عمومی واکنش های مثبت گسترده ای از سوی مخاطبان در سراسر جهان دریافت کرد و در میان دویست و پنجاه فیلم برتر در طول تاریخ از سوی سایت آی ام دی بی قرار گرفت.</p><br>
        <p class="infotext1">دسته بندی: کمدی ، انیمیشن ، فانتزی ، ماجراجویی</p>
        <h4 class="imgh4">تصاویر</h4>
        <div class="imginfo">
          <div class="imginfo-con">
            <div class="infogallery">
              <a target="_blank" href="{% static 'images/soul3.jpg'%}" >
                <img src="{% static 'images/soul3.jpg'%}" alt="روح۱" width="600" height="400">
              </a>
            </div>
          </div>


          <div class="imginfo-con">
            <div class="infogallery">
              <a target="_blank" href="{% static 'images/soul2.jpg'%}">
                <img src="{% static 'images/soul2.jpg'%}" alt="روح۲" width="600" height="400">
              </a>
            </div>
          </div>

          <div class="imginfo-con">
            <div class="infogallery">
              <a target="_blank" href="{% static 'images/soul5.jpg'%}">
                <img src="{% static 'images/soul5.jpg'%}" alt="روح۳" width="600" height="400">
              </a>
            </div>
          </div>

          <div class="imginfo-con">
            <div class="infogallery">
              <a target="_blank" href="{% static 'images/soul4.jpg'%}">
                <img src="{% static 'images/soul4.jpg'%}" alt="روح۴" width="600" height="400">
              </a>
            </div>
          </div>

        </div>
    </div>

    <div class="spacem"></div>
    <div class="footer-con">
      <div class="footer">
        <table align="center" class="tfooter">
          <tr>
            <td class="td"><a href="#" class="tdhover"> درباره وب موویز </a></td>
            <td class="td"><a href="#" class="tdhover"> تماس با ما </a></td>
          </tr>
          <tr>
            <td class="td"><a href="#" class="tdhover"> اپلیکشن ها </a></td>
            <td class="td"><a href="#" class="tdhover"> خرید اشتراک </a></td>
          </tr>
          <tr>
            <td class="td"><a href="#" class="tdhover">سوالات متداول</a></td>
            <td class="td"><a href="#" class="tdhover">قوانین و مقررات</a><td>
          </tr>
       </table>
       <div class="social"><a class="sociala"><img src="{% static "images/insta1.png" %}" class="icon"></a>
         <a class="sociala"><img src="{% static "images/Twitter.png" %}" class="icon"></a>
         <a class="sociala"><img src="{% static "images/tele.png" %}" class="icon"></a></div>
         <div class="endtext">
           <p> طراحی شده توسط احسانه طالب </p>
         </div>
       </div>
     </div>

  </body>

My_Django_stuff/first_project/templates/first_app/play.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>webmovies</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/mystyle.css" %}"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300&display=swap" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap" rel="stylesheet">


  </head>
  <body class="body">
    <video height="650px" width="100%" controls>
      <source src="{% static 'images/soul.mp4'%}" type='video/mp4'>
        Your browser does not support HTML video.
      </video>
  </body>
  </html>